// TypesFromSerializers CacheKey dcfddfef15e4cd8ff0948b1a0898a8e8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ContactsEdit {
      id: number
      account_id: number
      address?: string
      city?: string
      country?: string
      created_at: string | Date
      deleted_at?: string | Date
      email?: string
      first_name: string
      last_name: string
      organization_id?: number
      phone?: string
      postal_code?: string
      region?: string
      updated_at: string | Date
    }
  }
}
