/* eslint-disable import/exports-last */
// TypesFromSerializers CacheKey 4df4a17e96831a389b70f4253958b6f9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {};

declare global {
  namespace Schema {
    interface ContactsFormData {
      id?: number;
      account_id: number;
      address?: string;
      city?: string;
      country?: string;
      deleted_at?: string | Date;
      email?: string;
      first_name: string;
      last_name: string;
      organization_id?: number;
      phone?: string;
      postal_code?: string;
      region?: string;
    }
  }
}
