/* eslint-disable import/exports-last */
// TypesFromSerializers CacheKey e00a02fbf0edb8efec882dda4790e8c0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {};

declare global {
  namespace Schema {
    interface ContactsIndex {
      id: number;
      account_id: number;
      address?: string;
      city?: string;
      country?: string;
      created_at: string | Date;
      deleted_at?: string | Date;
      email?: string;
      first_name: string;
      last_name: string;
      organization_id?: number;
      phone?: string;
      postal_code?: string;
      region?: string;
      updated_at: string | Date;
    }
  }
}
