// TypesFromSerializers CacheKey b82eb974cd47ae9a14f3e7dcc7b2fd67
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ContactsShow {
      id: number
      account_id: number
      address?: string
      city?: string
      country?: string
      created_at: string | Date
      deleted_at?: string | Date
      email?: string
      first_name: string
      last_name: string
      organization_id?: number
      phone?: string
      postal_code?: string
      region?: string
      updated_at: string | Date
    }
  }
}
