// TypesFromSerializers CacheKey 3f297b3853fb8f8203fd9976ba23f3e5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface OrganizationsEdit {
      id: number
      account_id: number
      address?: string
      city?: string
      country?: string
      created_at: string | Date
      deleted_at?: string | Date
      email?: string
      name: string
      phone?: string
      postal_code?: string
      region?: string
      updated_at: string | Date
    }
  }
}
