// TypesFromSerializers CacheKey b90d858b25b871f35b0fae791da9979b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface OrganizationsFormData {
      id?: number
      account_id: number
      address?: string
      city?: string
      country?: string
      deleted_at?: string | Date
      email?: string
      name: string
      phone?: string
      postal_code?: string
      region?: string
    }
  }
}
