/* eslint-disable import/exports-last */
// TypesFromSerializers CacheKey 74bba37d18b1d64596d729636d04c5b4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {};

declare global {
  namespace Schema {
    interface OrganizationsIndex {
      id: number;
      account_id: number;
      address?: string;
      city?: string;
      country?: string;
      created_at: string | Date;
      deleted_at?: string | Date;
      email?: string;
      name: string;
      phone?: string;
      postal_code?: string;
      region?: string;
      updated_at: string | Date;
    }
  }
}
