/* eslint-disable import/exports-last */
// TypesFromSerializers CacheKey abe9e71417809f52c26d9eabd5afa225
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {};

declare global {
  namespace Schema {
    interface OrganizationsShow {
      id: number;
      account_id: number;
      address?: string;
      city?: string;
      country?: string;
      created_at: string | Date;
      deleted_at?: string | Date;
      email?: string;
      name: string;
      phone?: string;
      postal_code?: string;
      region?: string;
      updated_at: string | Date;
    }
  }
}
