// TypesFromSerializers CacheKey 016323a5a3ea8b6bba50d7afd48c7622
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Contact {
  id: number
  accountId: number
  address?: string
  city?: string
  country?: string
  createdAt: string | Date
  deletedAt?: string | Date
  email?: string
  firstName: string
  lastName: string
  organizationId?: number
  phone?: string
  postalCode?: string
  region?: string
  updatedAt: string | Date
}
