// TypesFromSerializers CacheKey 1f82e5bc9b5e0ddc5271cc6b161e7312
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Contact {
      id?: number
      account_id: number
      address?: string
      city?: string
      country?: string
      deleted_at?: string | Date
      email?: string
      first_name: string
      last_name: string
      organization_id?: number
      phone?: string
      postal_code?: string
      region?: string
    }
  }
}
