// TypesFromSerializers CacheKey 9f9cd0243334c062b509810a526d2303
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type AnyModel from '../AnyModel'

export default interface Model {
  id: AnyModel['id']
  name: AnyModel['name']
}
