// TypesFromSerializers CacheKey bad667166df9b788e6b636aa026e2c5b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Organization {
  id: number
  accountId: number
  address?: string
  city?: string
  country?: string
  email?: string
  name: string
  phone?: string
  postalCode?: string
  region?: string
}
