/* eslint-disable import/exports-last */
// TypesFromSerializers CacheKey 4116af7bacf017fd704cc1667ba455bb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {};

declare global {
  namespace Schema {
    interface Organization {
      id?: number;
      account_id: number;
      address?: string;
      city?: string;
      country?: string;
      deleted_at?: string | Date;
      email?: string;
      name: string;
      phone?: string;
      postal_code?: string;
      region?: string;
    }
  }
}
