// TypesFromSerializers CacheKey f1d215c128c9f094b7e81cdce37ad5f5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Model from './Model'

export default interface OrganizationWithContacts {
  id: number
  accountId: number
  address?: string
  city?: string
  contacts: Model[]
  country?: string
  createdAt: string | Date
  email?: string
  name: string
  phone?: string
  postalCode?: string
  region?: string
}
