// TypesFromSerializers CacheKey ca1ca29c66776be2a70c2be364a48780
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Model from './Model'

export default interface OrganizationWithContacts {
  id: number
  accountId: number
  address?: string
  city?: string
  contacts: Model[]
  country?: string
  email?: string
  name: string
  phone?: string
  postalCode?: string
  region?: string
}
