// TypesFromSerializers CacheKey 9afc7ef39e525348cc1e9a3e036a0c7b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Organization {
  id: number
  accountId: number
  address?: string
  city?: string
  country?: string
  createdAt: string | Date
  email?: string
  name: string
  phone?: string
  postalCode?: string
  region?: string
}
